# Generated by Django 4.2.1 on 2023-05-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StadiumTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_stadium', models.CharField(max_length=100)),
                ('tanggal', models.CharField(max_length=10)),
            ],
        ),
    ]
