# Generated by Django 4.2.1 on 2023-05-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penonton', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PertandinganTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pertandingan', models.CharField(max_length=100)),
            ],
        ),
    ]
